### PR TITLE
add NXdata/@auxiliary_signals  attribute

### LINKED ISSUE #815: NXdata auxiliary signals
Per [NIAC2018](https://www.nexusformat.org/NIAC2018Minutes.html) approved vote, 

> additional group level attribute auxiliary_signals which is an array of strings holding the names of additional signals to be plotted with the signal. They all need to be of the same shape.

### PR DESCRIPTION
**Pull request by prjemian**
fixes #815 per NIAC2018 approved vote

### CODE REVIEW

**Review by benajamin — COMMENTED** [review]
The second sentence is ambiguous. I suggest:
"Each auxiliary signal needs to be of the same shape as the default signal."

**Review by benajamin — COMMENTED** [review]
Further clarified:
"Array of strings holding the names of additional signals to
be plotted with the default signal (specified by the "signal" attribute).
Each auxiliary signal needs to be of the same shape as the default signal."

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
Thanks!

**Review by rayosborn — APPROVED** [review]

**Pull request merged**
