### PR TITLE
NXxpcs: add NXprocess group

### LINKED ISSUE #1006: NXxpcs: This is processed data, so it needs a [NXprocess](https://manual.nexusformat.org/classes/base_classes/NXprocess.html#nxprocess) group to document details of the reconstruction process.
This is processed data, so it needs a [NXprocess](https://manual.nexusformat.org/classes/base_classes/NXprocess.html#nxprocess) group to document details of the reconstruction process.

_Originally posted by @prjemian in https://github.com/nexusformat/definitions/issues/982#issuecomment-1058585665_

### PR DESCRIPTION
**Pull request by prjemian**
This is processed data, so it needs a [NXprocess](https://manual.nexusformat.org/classes/base_classes/NXprocess.html#nxprocess) group to document details of the reconstruction process.

- Close #1006

@ambarb @AbbyGI @JulReinhardt - can you comment?

### CODE REVIEW

**Comment by ambarb** [comment]
@prjemian if this is what NXprocess if for, then we should follow the convention.  I am not sure I would have realized this without your help

**Comment by JulReinhardt** [comment]
Yes, good point!

**Comment by prjemian** [comment]
This came up in discussions at the NIAC when we looked at the new contribution.  I, too, had completely overlooked NXprocess.  Thanks to @mkoennecke !

**Comment by prjemian** [comment]
Note: Similar uses in #997, #998

**Comment by prjemian** [comment]
@benajamin @ambarb @mkoennecke @RussBerg @woutdenolf This is ready for review.

**Review by woutdenolf — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
Thanks for the review!

**Pull request merged**
