### PR TITLE
consistent naming of parent_child fields

### LINKED ISSUE #791: Inconsistent field naming
There seems to be an inconsistency how fields are named. For example: `beam_center_x` vs. `x_pixel_size`. I think having `_x` as a suffix (like `beam_center_x`) would be preferable. What is the proper way to get this change considered?

### PR DESCRIPTION
**Pull request by prjemian**
fixes #791

### CODE REVIEW

**Comment by prjemian** [comment]
Merge is pending on [NIAC2020 vote](https://github.com/nexusformat/definitions/issues/791#issuecomment-707365329) approving this change.

**Review by PeterC-DLS — APPROVED** [review]
Although the example shows only siblings

**Comment by prjemian** [comment]
Good catch

**Comment by prjemian** [comment]
@PeterC-DLS Would mind re-reviewing the changed text?

**Review by yayahjb — APPROVED** [review]

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Review by benajamin — APPROVED** [review]

**Review by vasole — APPROVED** [review]

**Pull request merged**
