### PR TITLE
publish the docs as-is

### PR DESCRIPTION
**Pull request by prjemian**
- #1119

### CODE REVIEW

**Comment by prjemian** [comment]
It's not working:

```
Run ad-m/github-push-action@master
Push to branch gh-pages
Pushing to https://github.com/nexusformat/definitions.git
To https://github.com/nexusformat/definitions.git
 ! [rejected]          HEAD -> gh-pages (non-fast-forward)
error: failed to push some refs to 'https://github.com/nexusformat/definitions.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by prjemian** [comment]
@woutdenolf : How do we get the documentation to publish (per [#1145](https://github.com/nexusformat/definitions/pull/1145#issuecomment-1252499682))?

**Comment by woutdenolf** [comment]
The job "Build and Commit the User Manual" needs to be executed as well. But [as I said](https://github.com/nexusformat/definitions/pull/1145#issuecomment-1253379518) we should make a proper release because the docs already contain NeXus changes since 2022.07.

That being said, I already advocated to decouple tagging and deployment: https://github.com/nexusformat/definitions/issues/1029. I would like deployment to be a manual triggering of the CI with a variable (DEPLOY_HTML=true for example) that will trigger the deployment. @prjemian If you like that approach I can make a PR for that.

**Comment by prjemian** [comment]
I like that approach. It seems too early to release another full NXDL
version.

**Pull request closed without merging**
