### PR TITLE
NXxpcs: use a valid units type

### LINKED ISSUE #1204: Invalid units
https://github.com/nexusformat/definitions/blob/ea89964a412206b31e0b754bf95fad8e53f9650e/contributed_definitions/NXxpcs.nxdl.xml#L195

`units=NX_INT` is not  a valid token for dimensionality. Guess it shall be `NX_COUNT` or something else.

### PR DESCRIPTION
**Pull request by prjemian**
- close #1204

@tlcfem, @ambarb : your review comments are invited

### CODE REVIEW

**Review by TLCFEM — APPROVED** [review]
Fine with it. I presume 'NX_COUNT' is a good fit here since it is consistent with the doc.

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Review by prjemian — COMMENTED** [review]
DOC #1204 unnormalized units are not dimensionless

**Comment by prjemian** [comment]
@woutdenolf @PeterC-DLS Thanks for the reviews!

**Pull request merged**
