### PR TITLE
add NeXus Constructor and nxdl_to_hdf5.py

### LINKED ISSUE #972: NeXus Constructor and other utilities
@mkoennecke just told me about [NeXus Constructor](https://github.com/ess-dmsc/nexus-constructor), which I am very eager to play with. I feel that it should be listed in the [manual](https://manual.nexusformat.org/utilities.html). It doesn't seem to fit well with the existing categories, so I'll make a new one - maybe "Geometry".

Should we also list @RussBerg script for creating empty NeXus files from the NXDL definitions? Would it count as "validation", or need a new category? If anyone knows of a NeXus utility not already listed on the manual utilities page, then please speak up!

### PR DESCRIPTION
**Pull request by benajamin**
fixes #972

### CODE REVIEW

**Review by prjemian — APPROVED** [review]
LGTM

**Comment by prjemian** [comment]
@RussBerg Please review

**Review by RussBerg — CHANGES_REQUESTED** [review]
Hey @prjemian can you replace the lines for nxdl_to_hdf5.py with these?:

**nxdl_to_hdf5.py** is a python script that reads the NeXus definition files (i.e. nxdl.xml) and creates example python scripts as well as hdf5 files for each definition. There are generated example scripts of each application definition for both `h5py` and `nexusformat`. Currently, only application definitions and some contributed_definitions are supported as the code depends on the existence of an NXentry in the definition.

**Comment by prjemian** [comment]
@RussBerg please review

**Review by RussBerg — APPROVED** [review]
great thanks

**Pull request merged**
