### PR TITLE
Schema update 555

### PR DESCRIPTION
**Pull request by prjemian**
* changes to XML Schema, backwards-compatible
* #545 NXtransformations needs new units category: NX_TRANSFORMATION
* #546 NXmx use of `minOccurs` changed to `optional`
* #547 NXtransformations correction
* #556 allow declarations of dimensions for data values in attributes

locally: `utils/test_suite.py` passes and the Sphinx documentation builds

### CODE REVIEW

**Comment by prjemian** [comment]
We should bump the minor version number of the XML Schema.  Here is the definition from `nxdl.xsd`:

    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://definition.nexusformat.org/nxdl/3.1"
	xmlns:nx="http://definition.nexusformat.org/nxdl/3.1" 
	elementFormDefault="qualified">

BUT, that will change the namespace and that can have consequences that affect anything that uses the XML Schema.

**Should** we bump the minor version?  Any other way to differentiate from the previous XML Schema?

**Comment by prjemian** [comment]
@yayahjb Comments?  tacit approval is not satisfying

**Comment by prjemian** [comment]
I will examine the consequences of changing the minor version number *without* changing the namespace string.  It may well be that we leave the namespace string as-is, at least for now.

**Comment by zjttoefs** [comment]
Sorry, forgot to comment on the version number. I would say: Bump it. 
We might get away not changing it, but having version numbers we're too afraid to ever change is a bit pointless. We will see what breaks and have to prepare that for future updates.

**Pull request merged**
