### PR TITLE
document plot title and axis labels

### LINKED ISSUE #760: How to set the title of an NXdata?
I am missing a way to set the title of an NXdata plot. I can suggest the labels via the ``@long_name`` attribute but I miss the equivalent thing for the plot title.

Is there a solution existing/envisaged?

### PR DESCRIPTION
**Pull request by prjemian**
This addition of a`title` field to NXdata and additional documentation fixes #760, where it was asked how to find the plot title in the NeXus data file structure.

### CODE REVIEW

**Comment by vasole** [comment]
LGTM

**Comment by prjemian** [comment]
@vasole: Can you click the Approve button for your GitHub review?

**Comment by vasole** [comment]
The information is fine but the tests do not pass.

**Comment by vasole** [comment]
@prjemian 

No approve button available

**Comment by vasole** [comment]
Done,

**Comment by prjemian** [comment]
Thanks.  I see the reST/sphinx syntax error now.

**Comment by prjemian** [comment]
The syntax error was with XML, the reST/Sphinx syntax was correct.  When reST is embedded within an XML document, as is our documentation of NXDL structure, we can't use `<` at this time.  We might be able to use `&lt;` as a replacement if our nxdl2rst.py parser would make the correct conversions.  That would be an enhancement, for a separate issue.

**Comment by rayosborn** [comment]
Looks good to me too.

**Comment by prjemian** [comment]
Feel free to merge when you feel ready (either of you).  Might wait a couple days if there are comments from there.

**Comment by prjemian** [comment]
No additional comments received, merging now.

**Pull request merged**
