### PR TITLE
Run CI only for the main branch. Run syntax check for pull requests.

### LINKED ISSUE #1017: CI on the main branch only
Currently syntax checks and docs deployment workflows run on each push.

I propose to:

1. trigger github workflows only for events from the `main` branch
2. trigger the syntax workflow for pull request to the the `main` branch

This allows us to check whether all tests of a PR pass before merging it into the main branch.

### PR DESCRIPTION
**Pull request by woutdenolf**
Closes #1017

### CODE REVIEW

**Comment by woutdenolf** [comment]
This PR will cause all future pull requests to show the above when CI passes: "All checks have passed"

**Review by PeterC-DLS — APPROVED** [review]
Looks good to me

**Comment by prjemian** [comment]
Please do not merge this request yet.

**Comment by prjemian** [comment]
Title of this PR is misleading.  It says this PR will run CI only for the main branch.  This would exclude any CI process from testing whether the documentation will actually build on a branch **until** the branch is merged into main, removing valuable feedback to branch authors during the development process.

Instead of the proposed change to the publishing workflow, the existing workflow permits a build of the documentation but prevents uploading until a new version of the repository is *tagged*: https://github.com/nexusformat/definitions/blob/0dfc59a67263396cb4cbc437c9d2ee7c1d22cd09/.github/workflows/publish-sphinx.yml#L107-L109

I agree that the change to the syntax checks workflow appears to be an improvement.  Since [syntax checks](https://github.com/nexusformat/definitions/blob/0dfc59a67263396cb4cbc437c9d2ee7c1d22cd09/.github/workflows/syntax-checks.yml#L59) are part of the [publishing workflow](https://github.com/nexusformat/definitions/blob/0dfc59a67263396cb4cbc437c9d2ee7c1d22cd09/.github/workflows/publish-sphinx.yml#L34), the proposed change is already implemented if the publishing workflow remains unchanged.

**Review by prjemian — CHANGES_REQUESTED** [review]
These changes are not necessary.

**Comment by prjemian** [comment]
While we need a location to view documentation built in branches (very useful in the NIAC review process of contributed definitions, for example), to avoid confusion we should only publish documentation of *tagged* versions of the NeXus definitions.

**Comment by prjemian** [comment]
It would be nice to see the HTML documentation for any version of the NeXus standard (as much as may be made available).  An example is the documentation of Python as shown:
image

This would be in keeping with the [current release procedure (step 11)](https://github.com/nexusformat/definitions/wiki/Release-Procedure) and benefit the community.

Presently, a PDF copy of a tag is committed to the repository: https://github.com/nexusformat/definitions/tree/main/legacy_docs

**Comment by woutdenolf** [comment]
> These changes are not necessary.

These changes are necessary imo. When I review a PR I want to see a passing CI **before** I give the LGTM sign. This is common practice for every github/gitlab project I have been involved in. For example: [sphinx](https://github.com/sphinx-doc/sphinx/blob/4.x/.github/workflows/lint.yml#L3).

This PR is also removing CI for any other branch (hence the title) because changes always have to go through a pull request and we have a limited amount if CI jobs per day. If you're working on a branch and want to check CI: make a PR. This also removes the problem of solutions that are hiding in branches.

**Comment by woutdenolf** [comment]
For example https://github.com/nexusformat/definitions/pull/1019

I don't see a passing CI so if I were the reviewer I would never give the LGTM sign.

**Comment by woutdenolf** [comment]
I will split this PR in two different PRs: one for CI on PR and one for CI restricted to the main branch.

**Comment by woutdenolf** [comment]
Split in two different PR: #1024 #1025

**Pull request closed without merging**
