### PR TITLE
Issue 434

### PR DESCRIPTION
**Pull request by prjemian**

### CODE REVIEW

**Comment by prjemian** [comment]
@zjttoefs @rayosborn Can you look this over to see if it resolves all your concerns (except issues #436 & #437)?  If it is acceptable (make comment here), then I will merge it.

The only controversial item is that I marked the old signal/axes/axis attributes as deprecated (#435).  Might be better to invent yet another new attribute called "discouraged".  What do you think?

**Comment by zjttoefs** [comment]
I would have preferred a pull request that doesn't combine the build system change and editorial edits.

From what I can see briefly some of the examples are missing the axis_indices attributes. Those should be added. And the "axes" group attribute should be a string array, even in the simple 1D case. 

Otherwise I think there is no need to distinguish between "deprecated" and "discouraged". There are too many non-native speakers involved that don't get these nuances. Reluctant software people will interpret either as "still works, though".

I'm not sure about the apologetic tone that datarules.rst has on not using HDF5 dimension scales. They are not as powerful as our axes group attributes. At least last time I checked. It's nothing you introduced with these changes I believe but might we worth addressing while we're making edits in that area.

**Comment by prjemian** [comment]
No changes to the build system with this PR.  Those changes were 
complete in a previous PR.

Rather, one of the changes in this PR was to remove files marked with 
".obsolete" suffix.  That commit could be removed if it is out of place.

**Comment by rayosborn** [comment]
The nexusformat API cannot read the new axis_indices and they are not included in 99.99% of NeXus files created so far, so we had better proceed cautiously with the new system or it will just cause more confusion. I still think mandating the new system is a recipe for delaying NeXus adoption.

**Comment by prjemian** [comment]
The wording says the new method of signal/axes is "recommended" while 
the previous are marked "deprecated" with these changes.  This is the 
caution we are using, rather than mandating these changes.

**Comment by prjemian** [comment]
So, is this OK to merge?

**Comment by prjemian** [comment]
Sensing no objections, I'll merge tomorrow (~ 24h from now)

**Comment by zjttoefs** [comment]
Sorry, I was planning to merge that Tuesday but got interrupted. 
Merged now. It does not address all open problems in a final way but takes us in the right direction and there are tickets for the remaining items.

**Comment by zjttoefs** [comment]
Merged. (I thought Github might sense this.)

**Pull request closed without merging**
