### PR TITLE
Rewrite makefile, use in worfklows

### LINKED ISSUE #1131: Clean up the /Makefile and publishing workflow
While preparing the v2022.06 release, a problem (#1130) was discovered with the publishing workflow where some files for download were not being created in the workflow, but they were created in local development directories.  This was traced to differences in how the workflow builds the documentation.

As _Originally posted by @woutdenolf in https://github.com/nexusformat/definitions/issues/1130#issuecomment-1165892016_:  

> https://github.com/nexusformat/definitions/blob/ca8a3d56f05e59d8d31098da6a0f5b91842c9321/.github/workflows/publish-sphinx.yml#L38-L42
> https://github.com/nexusformat/definitions/blob/ca8a3d56f05e59d8d31098da6a0f5b91842c9321/.github/workflows/publish-sphinx.yml#L103-L115
> 
> And I don't see how `nxdl2rst` is supposed to be executed.

### PR DESCRIPTION
**Pull request by prjemian**
- close #1131

### CODE REVIEW

**Comment by prjemian** [comment]
Use micromamba instead of miniconda in workflow.  It is much faster to solve the package version requirements!

[Here](https://github.com/bluesky/hklpy/blob/f91c18df37ba4ce7feff52fbe60583ca0e106bef/.github/workflows/conda_unit_test.yml#L17-L21) is an example from the *hklpy* project:

```py
    - name: Create Python ${{ matrix.python-version }} environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yml
        environment-name: hklpy-test-${{ matrix.python-version }}
```

**Comment by prjemian** [comment]
With the `defaults` channel first, sphinx 3.4.3 was installed.  Current release is 5+.  Swap the order of the channels.

**Comment by prjemian** [comment]
In same Py3.10 install now, sphinx 5.0.2 is chosen.

**Comment by prjemian** [comment]
@PeterC-DLS @woutdenolf This is ready for review (acknowledging PR #1133 which proposes a new set of developer tools).

**Review by woutdenolf — APPROVED** [review]
Thanks @prjemian, this is a big improvement! Maybe a description somewhere what commands to execute in what situation (run tests, build manual, build impatient). 

Side note: why are we using conda? It works perfectly with a normal python environment.

**Comment by prjemian** [comment]
> Thanks @prjemian, this is a big improvement! Maybe a description somewhere what commands to execute in what situation (run tests, build manual, build impatient).
> 
> Side note: why are we using conda? It works perfectly with a normal python environment.

I agree with both your points.

**Comment by prjemian** [comment]
@woutdenolf Thanks for the review!

**Pull request merged**
