### PR TITLE
build & publish documentation to gh-pages from GitHub Actions workflow

### LINKED ISSUE #953: publish documentation from GitHub Actions workflow
Following #663 and related (nexusformat/wiki#4, #702, #868), the documentation built by a [jenkins workflow](https://github.com/nexusformat/definitions/blob/6759a1ef2f62f7742027828a8a007b3134fd6d6b/jenkins_build) running on a server at STFC-ISIS is published to the GitHub pages web site (reserved by GitHub) for the definitions repository.  That GitHub pages site, where the documentation is published, redirects to our manual.

https://nexusformat.github.io/definitions redirects _now_ to https://manual.nexusformat.org/

Recently, it has become quite simple to build and publish a repository to its gh-pages web site using a [GitHub Actions workflow](https://github.com/marketplace/actions/sphinx-to-github-pages) (and is [supported by Sphinx](https://sphinx-notes.github.io/pages/)), such as this example from the [apstools](https://github.com/BCDA-APS/apstools/blob/main/.github/workflows/publish-sphinx.yml) repository.

Our [syntax checking workflow](https://github.com/nexusformat/definitions/blob/main/.github/workflows/syntax-checks.yml) already builds the documentation with various Python versions.  An additional step (or a separate workflow) could publish after a successful build.  We could add restrictions that would only publish based on criteria, such as pushes to the `main` branch.

It is proposed to add such a workflow here, which would let us retire the service provided by ISIS (and detect problems such as #946 as they occur).  We could publish based on criteria, such as pushes to the `main` branch.

### PR DESCRIPTION
**Pull request by prjemian**
- FIX #953

### CODE REVIEW

**Comment by prjemian** [comment]
Note that until #950 is fixed (by PR #951) and merged into this branch, the _Syntax Checks / CI_ are expected to fail here.

**Comment by prjemian** [comment]
Let's disable the `syntax-checks.yml` workflow now to turn off the nuisance emails as they fail.

**Comment by prjemian** [comment]
Actually, this PR needs #951 first.

**Comment by prjemian** [comment]
Once the changes from #951 (which will fix the syntax checks) can be merged here, we can test the final publishing step.  (Without those fixes, the newly-prepared docs are missing quite a bit content.)  Only then would I consider this PR suitable for review.

@PeterC-DLS , @FreddieAkeroyd : That said, could either of you take a look at this before it is marked ready to review?

**Comment by prjemian** [comment]
To see how this has been run, consult the Actions logs for the _Publish Sphinx Docs to GitHub Pages_ workflow: https://github.com/nexusformat/definitions/actions/workflows/publish-sphinx.yml

**Comment by PeterC-DLS** [comment]
Looks okay but checks failing strangely...

**Comment by prjemian** [comment]
The Jenkins occurring must also be adjusted now since the PDFs have moved
from the `pdf/` directory (installed after the docs are built) to the
`_static` directory before the docs are built.

The CI failures will be resolved by the other PRi submitted last Friday.
That involves removing common indentation from embedded rst documentation
and use of an XML entity in a documentation block.

**Comment by PeterC-DLS** [comment]
That's not what the logs say: https://github.com/nexusformat/definitions/runs/4488225359?check_suite_focus=true

**Comment by prjemian** [comment]
Right.  That error has been appearing lately and looks like a problem with `pip`. Not something NeXus can resolve.

**Comment by prjemian** [comment]
related documentation to be adjusted:

```bash
(base) prjemian@zap:~/.../NeXus/definitions$ git grep /pdf/
manual/source/design.rst:.. [#] https://manual.nexusformat.org/pdf/NeXusIntern.pdf
manual/source/introduction-napi.rst:see the `NeXus Internals manual <https://manual.nexusformat.org/pdf/NeXusIntern.pdf>`_, copied from the NeXus code repository.
nxdl.xsd:                                                       http://manual.nexusformat.org/pdf/NeXusIntern.pdf
```

**Comment by prjemian** [comment]
@PeterC-DLS - Now I recall, the workflow failures involving `pip` were due to the incorrect instructions in `/environment.yml` that were fixed in #951 (by using a different YAML file for the GH workflow): https://github.com/nexusformat/definitions/blob/40bd56755e8e6d028e6a3b6be6489c44df81b240/environment.yml#L8-L9

**Comment by prjemian** [comment]
Is the `/environment.yml` file necessary now?

**Comment by prjemian** [comment]
Now that #951 is merged into this branch, the workflow failures (noted above) are resolved.

**Comment by prjemian** [comment]
@FreddieAkeroyd , @PeterC-DLS : Please review.

**Review by PeterC-DLS — APPROVED** [review]

**Comment by prjemian** [comment]
@FreddieAkeroyd Can you review this PR?

**Comment by prjemian** [comment]
I will merge this PR 2022-02-07 unless there are objections.

**Comment by FreddieAkeroyd** [comment]
Sorry @prjemian my GH notifications are all over the place. Should the actions be publishing to https://github.com/nexusformat/definitions/tree/gh-pages or do they publish elsewhere?

**Pull request merged**
