### PR TITLE
emphasize NXcollection is not validated

### LINKED ISSUE #1387: DOC: emphasize that content in NXcollection cannot be validated
Also, we should note that any and all content within a NXcollection group specified by an application definition cannot be validated.  NXcollection is and will always be for unvalidated content.  This should be made clear in future NIAC reviews of contributed definitions and made clear in the documentation of NXcollection, with a suggestion to use NXparameters instead.

_Originally posted by @prjemian in https://github.com/nexusformat/definitions/issues/1386#issuecomment-2112919873_

### PR DESCRIPTION
**Pull request by prjemian**
- close #1387

### CODE REVIEW

**Comment by prjemian** [comment]
@jkotan - Is this what you had in mind?

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Comment by jkotan** [comment]
Yes. Does NXpatameters class can be placed in any location below NXentry (similarly to NXcollection)?

**Comment by prjemian** [comment]
Yes.  It's in the NXentry group docs:
image

**Pull request merged**
