### PR TITLE
Updates from NIAC 2016

### PR DESCRIPTION
**Pull request by phyy-nx**
Action items from minutes completed:
-H,K,L change to NX_number for incommensurate structures
-Discussion on flags, change to bitfield, no enum for efficiency
-Expand the description of partiality
-Need to keep mm and pixel positions because of parallax
-Write out predicted and observed
-Drop the mm in names, rather use units
-bounding_box as array, document the usage
-Spell out background
-Drop the val on the intensities, keep the _var version
code is not in place we defer it for now.
-Add polar_angle and azimuthal_angle

TODO
-Need documentation for polar_angle and azimuthal_angle
-Need to add some examples of flags. Would like to use the DIALS flags.

Deferred:
-overlaps is a list of overlapped reflections. This is a ragged array. As the

### CODE REVIEW

**Comment by zjttoefs** [comment]
This should have addressed all NIAC comments.

**Comment by prjemian** [comment]
In the *flags* fields, there is bit 17: ``bad_shoebox``.  It is not obvious what is a *shoebox* in this context.

**Comment by phyy-nx** [comment]
dials/dials#363 aims to document all these flags, including `bad_shoebox`.  When those doc strings are in place, I'll put them here.

Question about the first dim "n" for the bounding box.  Should all the other columns have 'n' as a dimension?  For example, 'h', 'k', and 'l' should all be arrays of dimension n.

**Comment by prjemian** [comment]
> Should all the other columns have 'n' as a dimension? For example, 'h', 'k', and 'l' should all be arrays of dimension n.

The existing NXDL files are not consistent in this regard.  Yours is a good idea, fits the current circumstances, and would inspire us to revise NXDL files similarly.  One reason for the inconsistency in other NXDL files is that some *fields* have a variable [shape](https://duckduckgo.com/?q=hdf5+dataset+shape&t=ffsb&ia=web).

**Comment by phyy-nx** [comment]
Cool.  I'll get that going then.

**Pull request merged**
