### PR TITLE
Fix wrong category for NXsnsevent application definition

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Review by woutdenolf — COMMENTED** [review]
No idea what this should be.

**Review by woutdenolf — APPROVED** [review]
Well I guess it's not that different from NXsnshisto. So LGTM.

**Comment by prjemian** [comment]
Both NXsnshisto and NXsnsevent should be base classes.

**Comment by prjemian** [comment]
But SNS has never asked for them to be ratified by the NIAC.

**Comment by PeterC-DLS** [comment]
I guess we can deprecated them in next release...

**Comment by woutdenolf** [comment]
> Both NXsnshisto and NXsnsevent should be base classes.

So either undo https://github.com/nexusformat/definitions/pull/1161 and both remain base classes or merge this PR and both are application definitions.

**Comment by PeterC-DLS** [comment]
They are both application definitions, right? They both specify `NXentry`.

**Comment by prjemian** [comment]
> I guess we can deprecated them in next release...

That might be a good question for @peterfpeterson (one of the original authors) or @kedokudo (the current SNS rep on the NIAC).

**Comment by prjemian** [comment]
> They are both application definitions, right? They both specify `NXentry` and set `definition` fields!

OK.  I confess this was all I examined today:

```bash
(bluesky_2022_3) prjemian@zap:~/.../NeXus/definitions$ git grep category | grep NXsns
contributed_definitions/NXsnsevent.nxdl.xml:<definition type="group" name="NXsnsevent" category="base" extends="NXobject"
contributed_definitions/NXsnshisto.nxdl.xml:<definition type="group" name="NXsnshisto" category="base" extends="NXobject"
```

**Review by prjemian — APPROVED** [review]
yes

**Pull request merged**
