### PR TITLE
Define use_application_defaults only once

### LINKED ISSUE #1155: use_application_defaults asignment is wrong
This

https://github.com/nexusformat/definitions/blob/1ac17ef55af511113458699889691d28052a8d58/utils/nxdl2rst.py#L559

should be like this

https://github.com/nexusformat/definitions/blob/1ac17ef55af511113458699889691d28052a8d58/utils/nxdl2rst.py#L681

### PR DESCRIPTION
**Pull request by woutdenolf**
- Closes #1155

### CODE REVIEW

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Comment by PeterC-DLS** [comment]
I have to check `NXcsg` for required logic as it's different in https://raw.githubusercontent.com/nexusformat/definitions/main/legacy_docs/nexus-v2020.10-2020-12-08-0649b8a4.pdf

**Comment by woutdenolf** [comment]
> I have to check `NXcsg` for required logic as it's different in https://raw.githubusercontent.com/nexusformat/definitions/main/legacy_docs/nexus-v2020.10-2020-12-08-0649b8a4.pdf

You need to check before I merge or can I merge?

**Comment by PeterC-DLS** [comment]
Yes, I will double-check a selection of definitions

**Comment by PeterC-DLS** [comment]
Ok, `NXcsg` has no `required` or `minOccurs=1` set so okay with generation. There's a separate issue with whether it should; also `NXsnsevent` and `NXsnshisto` has wrong category. I will fixed latter for release.

**Review by PeterC-DLS — APPROVED** [review]
LGTM (though new global is also passed around too - one for the refactor)

**Comment by woutdenolf** [comment]
> LGTM (though new global is also passed around too - one for the refactor)

Yes indeed. I missed that. Not important. `dev_tools` replaces all that.

**Pull request merged**
