### PR TITLE
Pdb in nexus

### PR DESCRIPTION
**Pull request by yayahjb**
I believe the pdb_in_nexus branch is ready to merge into master.  There are other changes that will be needed to clarify use, but I would suggest they belong in cnxvalidate, inasmuch as they relate to hooking validation against nxdl definitions to validation against the PDB dictionaries. -- Herbert

### CODE REVIEW

**Comment by zjttoefs** [comment]
I made some edits to the documentation. Otherwise as discussed in the Telco on Tuesday, we should have the means to validate any NeXus contents after conversion to PDB/CIF land. A tool that does the conversion makes it so much more reliable.

**Comment by prjemian** [comment]
Should this close #553 when merging?

**Comment by prjemian** [comment]
Checked that the documentation will build properly and fixed a couple problems in #615.  I'm OK with this PR.

**Comment by prjemian** [comment]
travis-ci reports an error with the NXDL:

```
NXDL_Invalid: base_classes/NXpdb.nxdl.xml : Element '{http://definition.nexusformat.org/nxdl/3.1}definition', attribute 'version': The attribute 'version' is not allowed., line 35
```

remove the `@version` attribute

**Comment by prjemian** [comment]
travis-ci reports another error:

```
Exception: Bad indentation in <doc> of NXpdb [	       which converts to::]: expected "\t\t" found "\t       which converts to::".
```

please fix this.  You need to indent the code example block that [follows](https://github.com/nexusformat/definitions/blob/397f06c4ab46fd984b8676230ea642b6afb82ffb/base_classes/NXpdb.nxdl.xml#L162)

**Comment by yayahjb** [comment]
Hopefully both travis-ci errors are fixed -- Herbert

**Comment by prjemian** [comment]
@yayahjb : This is now ready to merge.  Closes both #614 and #553, correct?

**Comment by prjemian** [comment]
Hold it, there is a conflict due to #623 where version attribute was removed.  This fork needs master to be merged in first to resolve this conflict.  *Then*, the `version` attribute will be removed.

**Comment by prjemian** [comment]
I'll merge tomorrow unless I hear objections.

**Comment by prjemian** [comment]
change the name of this PR to show where the work is to be found

**Pull request merged**
