### PR TITLE
complex units, such as eV/mm

### LINKED ISSUE #1435: complex units, like eV/mm
- [ ] Neither NX_ENERGY nor NX_PER_LENGTH is the correct choice for eV/mm as monochromator disperion is reported at FLASH
- [ ] NeXus doc states ["However, any field must have a units attribute which describes the units."](https://manual.nexusformat.org/datarules.html#index-26) but hardly anybody does this via adding an attribute named  "units" to **all** fields, i.e. also fields NX_CHAR must have a units attribute, feels that this is too tight of being a useful constraint.
- [ ] #1487

### PR DESCRIPTION
**Pull request by prjemian**
- close #1435

### CODE REVIEW

**Comment by prjemian** [comment]
@sanbrock What else needs to be done to make this PR ready for review?

**Comment by prjemian** [comment]
CI reports a build error but no specifics.  Locally, I see this problem after running `make prepare html`:

```
...projects/NeXus/definitions/build/manual/source/classes/contributed_definitions/NXimage_set_em_bf.rst:document isn't included in any toctree
```

Not seeing that NXDL file:

```
(bluesky_2024_3) prjemian@arf:~/.../NeXus/definitions$ ls -1 contributed_definitions/NXimage*
contributed_definitions/NXimage_set_em_adf.nxdl.xml
contributed_definitions/NXimage_set_em_kikuchi.nxdl.xml
contributed_definitions/NXimage_set.nxdl.xml
```

**Comment by prjemian** [comment]
How about this?

image

**Review by sanbrock — APPROVED** [review]
LGTM

**Pull request merged**
