### PR TITLE
NXstage contributed class

### PR DESCRIPTION
**Pull request by mtwharmby**
Class to describe concerted motion of a set of NXpositioners, for example a diffractometer
or a collection of piezoelectric positioners in a mirror.

Signed-off-by: Michael Wharmby <michael.wharmby@diamond.ac.uk>

### CODE REVIEW

**Comment by prjemian** [comment]
Regarding how to use names which are not defined by the NXDL spec, there is an issue (https://github.com/nexusformat/definitions/issues/562) to standardise amongst the NXDL files.  I recommend that you comment on that issue, then modify the NXDL file (and update this PR) accordingly.  This will enable automated processing of NXDL files (such as for data file validation) to recognize when a name is allowed to vary.

**Comment by prjemian** [comment]
@mtwharmby :
I've given you a [PR](https://github.com/mtwharmby/definitions/pull/1) with proposed changes.  If you agree, merge that into this PR and I will merge here.

**Comment by mtwharmby** [comment]
Thanks very much. I'll review the changes and push them in. I've been talking to @markbasham about this offline and also following from the telco I think the structure of this is going to change slightly, but will certainly include your changes. Thanks again!

**Comment by mtwharmby** [comment]
It's a typo. Because I was rushing. Sorry!

**Comment by mtwharmby** [comment]
Don't have time to fix this for today's telco and I think I've not expressed what I wanted to do very well with this. Will discuss more offline with @markbasham and others and put in a fresh pull request.

**Pull request closed without merging**
