### PR TITLE
update the change history

### LINKED ISSUE #1197: update the change history for NIAC2022 work
Several pull requests have been merged during NIAC202 (and before).  Update the change history accordingly.

### PR DESCRIPTION
**Pull request by prjemian**
- close #1197

### CODE REVIEW

**Comment by prjemian** [comment]
Summarizes history from closed PRs since previous release.

**Comment by prjemian** [comment]
**New** contributors?

**Comment by rayosborn** [comment]
I don't think this involved non-NIAC members.

**Comment by rayosborn** [comment]
Nice work getting it to pass all the checks. Sorry for all the typos.

**Comment by prjemian** [comment]
So, no issues from new contributors since August?

**Comment by prjemian** [comment]
Such as #1184, but this is not yet resolved.  So, not on the change history yet.

**Review by woutdenolf — APPROVED** [review]

**Comment by prjemian** [comment]
@woutdenolf Thanks for the review!

**Pull request merged**
