### PR TITLE
Add Electron Source as one of the NXsource types

### PR DESCRIPTION
**Pull request by phyy-nx**
Part of work @dagewa has been doing on making some MicroED NeXus files.

### CODE REVIEW

**Comment by sanbrock** [comment]
An Electron Microscope is a complex device, maybe "electron beam" would be more appropriate. Note that details of an EM can be registered in [NXem](https://manual.nexusformat.org/classes/contributed_definitions/NXem.html)

**Comment by phyy-nx** [comment]
Feedback from the Telco: we ask @sanbrock to meet with @dagewa to meet and come up with a reconciled proposal between NXem and this PR, specifically "Electron Microscope" vs. "Electron beam" vs. "Electron gun" vs. "Cathode ray", or similar.  The idea is to have a proposal in time for the June code camp NIAC meeting so it can be voted on.  Thanks!!

**Comment by PeterC-DLS** [comment]
Also note that there are many types of electron guns...

**Comment by phyy-nx** [comment]
Updated now with changes from #1268

**Comment by dagewa** [comment]
I guess we should change the title? (I don't have edit access)

**Review by yayahjb — APPROVED** [review]
Worth doing

**Comment by PeterC-DLS** [comment]
This has been duplicated by #1268

**Pull request closed without merging**
