### PR TITLE
Add per-image dynamic_mask as option for NXdetector. Resolves #651.

### LINKED ISSUE #651: Need per-image pixel mask
The NXmx specification of pixel_mask is:

`pixel_mask[i, j, k]: (optional) NX_INT`

This specifies a single mask applicable to all images in the dataset.  This is a valid use case.  I believe it could also be defined as:

`pixel_mask[np, i, j, k]: (optional) NX_INT`

i.e., it is valid for the user to provide a separate mask for each image.  This is the case for the EuXFEL.

Therefore, the pixel mask always has a number of dimensions equal to the dimensionality of the data OR the dimensionality of the data -1, where the former is for a mask for each image and the later is a mask for the whole dataset.

Thoughts?

### PR DESCRIPTION
**Pull request by phyy-nx**
Also sync documentation between NXmx and NXdetector.

Alternate solution to #651 than what I did in #654.  Pending discussion.

### CODE REVIEW

**Comment by phyy-nx** [comment]
Updated branch taking into account #654.

**Comment by phyy-nx** [comment]
Updates from telco applied

**Comment by prjemian** [comment]
@yayahjb : Can you review?

**Comment by prjemian** [comment]
@phyy-nx:  This PR is languishing.  Should we merge without review from @yayahb?

**Comment by phyy-nx** [comment]
Hi, I've rebased against master.  Unless there are no objections, I'm happy to merge.  I'll merge by Wednesday, end of day PST?  Thanks!

**Pull request merged**
