### PR TITLE
fix example nxdl.xml files so they pass the syntax checks

### PR DESCRIPTION
**Pull request by woutdenolf**

### CODE REVIEW

**Review by prjemian — COMMENTED** [review]
Great!  Are these files tested by the util/test_suite.py?

**Comment by woutdenolf** [comment]
> Great! Are these files tested by the util/test_suite.py?

They are tested by the new `dev_tools` (https://github.com/nexusformat/definitions/pull/1133). It doesn't restrict itself to the three directory `base_classes`, `applications` and `contributed_definitions`. Every nxdl.xml file it finds in the repo is tested.

**Review by prjemian — APPROVED** [review]
OK

**Comment by prjemian** [comment]
After merging, we should tag another rc version.  Looks like that should be `v2022.06rc4:

```bash
(bluesky_2022_2) prjemian@zap:~/.../NeXus/definitions$ git tag | grep v202
v2020.1
v2020.10
v2020.1rc1
v2020.1rc2
v2022.06rc0
v2022.06rc1
v2022.06rc2
v2022.06rc3
```

**Comment by prjemian** [comment]
-er- this new tag comment was intended as a comment for the dev_tools PR #1133.

**Pull request merged**
