### PR TITLE
document all the new anchors in one page

### LINKED ISSUE #879: nxdl2rst.py: document all the new anchors in one page
Build a documentation page (separate? not part of the manual?), organized by keyword and context, listing all the anchors defined by #878.

For example, given the reST anchor `/NXdata/VARIABLE@last_good-attribute` (corresponds with HTML anchor `#nxdata-variable-last-good-attribute`), the keyword would be `@last_good` (converted to lower case) and the context would be `/NXdata/VARIABLE@last_good-attribute` with a link to the manual page anchor.  Any keyword with multiple contexts would be listed together, such as

* data
    * `/NXdata/DATA-field`
    * `/NXdetector/data-field`
    * `/NXentry/DATA-group`
  ..

Consider registering this list (2,517 items now) with an external registry, such as https://www.pidconsortium.net/.  [More details](http://dtr-test.pidconsortium.eu/#urls/intro.html)

### PR DESCRIPTION
**Pull request by prjemian**
- close #879

### CODE REVIEW

**Comment by prjemian** [comment]
To keep this PR focused, will not work on #1057 and #1059 in this PR.

**Comment by prjemian** [comment]
@PeterC-DLS @sanbrock @woutdenolf This is ready for review.  Need to checkout the branch and build locally to view the content.  `make local`

**Comment by prjemian** [comment]
Here is where the new content is referenced:
Clipboard01

This is a view of the HTML page (just the first part): 
Clipboard012

YAML content starts like this:

```yaml
_metadata:
  datetime: '2022-06-18T19:25:37.457455'
  subtitle: Anchors for all NeXus fields, groups, attributes, and links.
  title: NeXus NXDL vocabulary.
terms:
  '@auxiliary_signals':
    /NXdata@auxiliary_signals-attribute:
      html: '#nxdata-auxiliary-signals-attribute'
      term: /NXdata@auxiliary_signals-attribute
      url: https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-auxiliary-signals-attribute
  '@axes':
    /NXcxi_ptycho/DATA@axes-attribute:
      html: '#nxcxi-ptycho-data-axes-attribute'
      term: /NXcxi_ptycho/DATA@axes-attribute
      url: https://manual.nexusformat.org/classes/applications/NXcxi_ptycho.html#nxcxi-ptycho-data-axes-attribute
    /NXcxi_ptycho/entry_1/instrument_1/detector_1/translation@axes-attribute:
      html: '#nxcxi-ptycho-entry-1-instrument-1-detector-1-translation-axes-attribute'
      term: /NXcxi_ptycho/entry_1/instrument_1/detector_1/translation@axes-attribute
      url: https://manual.nexusformat.org/classes/applications/NXcxi_ptycho.html#nxcxi-ptycho-entry-1-instrument-1-detector-1-translation-axes-attribute
    /NXcxi_ptycho/entry_1/instrument_1/detector_1@axes-attribute:
      html: '#nxcxi-ptycho-entry-1-instrument-1-detector-1-axes-attribute'
      term: /NXcxi_ptycho/entry_1/instrument_1/detector_1@axes-attribute
      url: https://manual.nexusformat.org/classes/applications/NXcxi_ptycho.html#nxcxi-ptycho-entry-1-instrument-1-detector-1-axes-attribute
    /NXdata/DATA@axes-attribute:
      html: '#nxdata-data-axes-attribute'
      term: /NXdata/DATA@axes-attribute
      url: https://manual.nexusformat.org/classes/base_classes/NXdata.html#nxdata-data-axes-attribute
```

**Review by PeterC-DLS — APPROVED** [review]
LGTM

**Pull request merged**
