### PR TITLE
Table of Hypertext Anchors just needs first column 

### LINKED ISSUE #1108: nxdl2rst.py: Table of Hypertext Anchors just needs first column
In the documentation of each NXDL, there is a Table of Hypertext Anchors, such as this from [NXaperture](https://manual.nexusformat.org/classes/base_classes/NXaperture.html#hypertext-anchors):
Clipboard01

Since both columns link to the same content (#879 will provide related information), only the first column is necessary.

### PR DESCRIPTION
**Pull request by prjemian**
- close #1108
As described by @sanbrock

### CODE REVIEW

**Review by woutdenolf — APPROVED** [review]
LGTM

For reference, it looks like this now:
image

**Review by PeterC-DLS — COMMENTED** [review]
If this is the only place that used pyRestTable then can remove it as a dependency from package

**Comment by prjemian** [comment]
still in `utils/nxdl2rst.py`:

```bash
(bluesky_2022_2) prjemian@zap:~/.../NeXus/definitions$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
(bluesky_2022_2) prjemian@zap:~/.../NeXus/definitions$ git pull
Already up to date.
(bluesky_2022_2) prjemian@zap:~/.../NeXus/definitions$ git grep -i pyresttable
.github/env-workflow.yml:  - pyRestTable
requirements.txt:pyRestTable
utils/nxdl2rst.py:import pyRestTable
```

**Comment by PeterC-DLS** [comment]
Pete, you removed the only user (previous line 45 onwards) in this PR.

**Comment by prjemian** [comment]
Ok, will remove the pyRestTable requirement, as you said. And the one unused import.

**Pull request merged**
