### PR TITLE
fix name of azimuthal angle in doc string

### LINKED ISSUE #325: NXtofraw explains azimuthal_angle as "polar angle"
... and check whether copy&paste has propagated this error

### PR DESCRIPTION
**Pull request by benajamin**
fixes #325

### CODE REVIEW

**Comment by benajamin** [comment]
also fixes https://github.com/nexusformat/NIAC/issues/62
I don't think we need NIAC approval for this bug fix.

**Review by prjemian — APPROVED** [review]
Looks obvious and correct.  Good catch by@jwuttke.

**Comment by prjemian** [comment]
> also fixes [nexusformat/NIAC#62](https://github.com/nexusformat/NIAC/issues/62) I don't think we need NIAC approval for this bug fix.

I agree.  It is _only_ a change in documentation so no existing data files or writers will be affected by this change.

**Comment by prjemian** [comment]
When merging, also close the [NIAC issue](https://github.com/nexusformat/NIAC/issues/62).

**Pull request merged**
