### PR TITLE
Use style file when creating latex index

### LINKED ISSUE #1141: Latex index creation misses use of style file
This leads to warnings like this:
```
[161] (./nexus.ind [162]
! Undefined control sequence.
<argument> \spxpagem 
                     
l.22 		\hyperindexformat{\spxpagem}{127}
                                        
! Undefined control sequence.
<argument> \spxpagem 
...

### PR DESCRIPTION
**Pull request by PeterC-DLS**
Fixes #1141

### CODE REVIEW

**Review by prjemian — APPROVED** [review]
Ok.  Will be obsolete by #1133?

**Comment by PeterC-DLS** [comment]
I'm not sure we should merge such a large PR before a release but let me check it out tomorrow.

**Comment by woutdenolf** [comment]
> I'm not sure we should merge such a large PR before a release but let me check it out tomorrow.

Yes we need to discuss this properly. It's a big change.

**Comment by woutdenolf** [comment]
> Ok. Will be obsolete by #1133?

Yes but a simple `sphinx>5` requirement will do.

**Comment by PeterC-DLS** [comment]
I was testing the pdf build in a Centos 8 container with sphinx < 3!

**Comment by woutdenolf** [comment]
That's why I added the [`install`](https://github.com/woutdenolf/definitions/blob/00fcbfc7ec352addfc4c9fde6df20a56c8219056/Makefile#L17) command to the make file in #1133

**Pull request merged**
