### PR TITLE
[releng] Publish manual for v2022.06 release

### PR DESCRIPTION
**Pull request by PeterC-DLS**
Release tagged and created

### CODE REVIEW

**Review by prjemian — APPROVED** [review]
Changed the PR title for the release this documents.

**Comment by PeterC-DLS** [comment]
Do you mean this release 2022.06?

**Review by woutdenolf — APPROVED** [review]

**Comment by woutdenolf** [comment]
The title says

```
[releng] Publish manual for (previous) v2020.10 release 
```

but it should probably say

```
[releng] Publish manual for the v2022.06 release 
```

Unless you really wanted to add the PDF of v2020.10, in which case the pdf fle is the wrong one.

**Comment by prjemian** [comment]
The proposed PDF was for v2020.10.  Per [release procedure](https://github.com/nexusformat/definitions/wiki/Release-Procedure), step 10:

> 10. build a PDF version of the (new version of the) manual
> 
>     - follow the naming pattern [now in use](https://github.com/nexusformat/definitions/issues/597) (year.month, the old style was major.minor)
>     - nexus- + release name + yyyy-mm-dd + GitHub commit code + .pdf
>     - example new way: nexus-v2018.4-2018-04-30-abc1234.pdf

Looks good but content was not for the new version.

**Comment by PeterC-DLS** [comment]
Cache/CDN failure? I see
nexus-manual-title  and 
nexus-manual-contrib at https://github.com/nexusformat/definitions/blob/add-2022-06-pdf/legacy_docs/nexus-v2022.06-2022-07-05-1572327.pdf

**Comment by woutdenolf** [comment]
I can confirm that the committed PDF is v2022.06 This corresponds to the name of the file and the title of the PR.

Note that v2020.10 was already added in the past: https://github.com/nexusformat/definitions/commit/22b581d946ad0dc645518d85c3cb3bc6fd773d38

**Pull request merged**
